version: '3.7'

networks:
  adidas-net:
    driver: bridge

services:
  eureka-server:
    build: ./eureka
    image: adidas/eureka-server
    networks:
      - adidas-net
    ports:
      - "8761:8761"
    environment:
      eureka.instance.hostname: eureka-server
      eureka.client.serviceUrl.defaultZone: http://eureka-server:8761/eureka
  subscription-service:
    build: ./subscription
    image: adidas/subscription-service
    networks:
      - adidas-net
    ports:
      - "8088:8088"
    depends_on:
      - eureka-server
    links:
      - email-service
    environment:
      eureka.client.serviceUrl.defaultZone: http://eureka-server:8761/eureka
  email-service:
    build: ./email
    image: adidas/email-service
    networks:
      - adidas-net
    ports:
      - "8087:8087" 
  authentication-service:
    build: ./authentication
    networks:
      - adidas-net
    ports:
      - "6000:6000"
    depends_on: 
      - eureka-server
    environment:
      eureka.client.serviceUrl.defaultZone: http://eureka-server:8761/eureka
  public-gateway-service:
    build: ./gateway
    image: adidas/public-gateway-service
    networks:
      - adidas-net
    ports:
      - "8080:8080"
    depends_on:
      - eureka-server
      - subscription-service
      - authentication-service
    environment:
      eureka.client.serviceUrl.defaultZone: http://eureka-server:8761/eureka